### ISSUE TITLE
Untracking the DbSqlite File

### ISSUE THREAD

**Issue by tngeene** [Kudzmat/NoseBleedSection#4]
It is generally not recommended to track the dbsqlite file in version control since it is created on every instance. Tracking this file can lead to unnecessary version conflicts and bloated repositories. Therefore, it would be beneficial to untrack the dbsqlite file from the project's version control system.

**Comment by Kudzmat** [comment]
Thank you for raising this issue; it is sorted!

**Comment by tngeene** [comment]
you need to include the untracked files in the .gitignore file otherwise they'll still be tracked on the next push.

example https://github.com/tngeene/django-task-manager/blob/main/.gitignore

**Comment by Kudzmat** [comment]
Thanks, I appreciate it. I've now added many files to .gitignore; let me know if everything is set.

**Comment by tngeene** [comment]
don't know why you're untracking [dockerfile and docker-compose](https://github.com/Kudzmat/NoseBleedSection/blob/master/.gitignore#L31-L33)?

**Comment by Kudzmat** [comment]
I don't have any docker related files for the project yet but I premtively untracked them to avoid future problems since configurations typically vary depending on the deployment environments.

**Comment by tngeene** [comment]
I doubt it. Docker is the deployment configuration, it's a write once, deploy anywhere tool. I don't see why you should untrack the docker files even though you don't have it now.

**Comment by Kudzmat** [comment]
Ok, I have no issues amending that. Is there anything else you've picked up on that needs to be amended?

**Comment by tngeene** [comment]
> Ok, I have no issues amending that. Is there anything else you've picked up on that needs to be amended?

No, all good. I can start contributing to the project

**Comment by Kudzmat** [comment]
Excellent, thanks. I appreciate the help!
