### ISSUE TITLE
Untrack the .idea file

### ISSUE THREAD

**Issue by tngeene** [Kudzmat/NoseBleedSection#5]
It is necessary to untrack the .idea file because it contains IDE-specific configuration that is not relevant to the project or other contributors.

Keeping the .idea file tracked in Git can lead to conflicts and unnecessary merge conflicts, especially when multiple contributors are working on the same project. Additionally, this file can contain sensitive information such as usernames, passwords, and API keys that should not be shared publicly.

Untracking the .idea file allows for a cleaner and more focused version control history. which helps to ensure that only relevant changes to the project are being tracked and committed to Git

**Comment by Kudzmat** [comment]
Issue is sorted, thank you!
